### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by Smorsmi** [r00li/Aibo-ERS-xxx-battery#4]
Hi, I am wondering what the pinholes on the pcb are and if they need to be masked off or anything?

**Comment by r00li** [comment]
If you mean the 6 metalized holes - those are for the battery pack connector. It's how the pack connects to the Aibo.

**Comment by Smorsmi** [comment]
Negative, the pinholes/vias on the pads. I can't tell if they are an artefact from software or intended. The pcb manufacturer has brought it up with me.

**Comment by r00li** [comment]
Ah, vias... then yes, they are intended.

If you mean these for example:
<img width="914" alt="Screenshot 2024-08-07 at 17 59 54" src="https://github.com/user-attachments/assets/9c0941ca-f4a9-48f9-8275-0800875d6d7c">

**Comment by Smorsmi** [comment]
Awesome, that solves my confusion, I just wanted to confirm im not crazy haha. Thankyou for your reply. I don't usually ask questions much.

**Comment by r00li** [comment]
No worries, I am glad to help.
